.PHONY: all build

all: build

/netronner-build/netronner-webapi/Makefile:
	cp -r /netronner-src /netronner-build

build: /netronner-build/netronner-webapi/Makefile
	cd /netronner-build/netronner-webapi && \
	$(MAKE) distclean && \
	$(MAKE) all && \
	$(MAKE) tarball; \
	TARBALL_NAME=$$(find rel/ -name 'netronner*.tar.gz'); \
	cp $$TARBALL_NAME /netronner-src/netronner-webapi
